### PR TITLE
Add a fully configured Xcode project

### PR DESCRIPTION
**Pull request by BaBrixx**
This pull request adds an Xcode project that builds and bundles the extension in an macOS and iOS app

### CODE REVIEW

**Review by NybyDK — DISMISSED** [review]
this is fucking  garbage

**Comment by NybyDK** [comment]
it autocorrected glamorous*

**Review by NybyDK — DISMISSED** [review]
this is one of the most code ever

**Review by atjn — DISMISSED** [review]
Xcode be like 
photograph-nickelback

**Review by AlbertHald — APPROVED** [review]
image

**Pull request merged**
